---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sched.io
  resources:
  - schedulercontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sched.io
  resources:
  - schedulercontrollers/finalizers
  verbs:
  - update
- apiGroups:
  - sched.io
  resources:
  - schedulercontrollers/status
  verbs:
  - get
  - patch
  - update
